apply john marshall's patch

diff --git a/BuildUnix/configure b/BuildUnix/configure
--- a/BuildUnix/configure
+++ b/BuildUnix/configure
@@ -2218,7 +2218,7 @@ if test "${with_fltk+set}" = set; then
   
 	CPPFLAGS="${CPPFLAGS} -I$withval/include"
 	LDFLAGS="${LDFLAGS} -L$withval/lib"
-
+	test "${FLUID+set}" != set && test -r "$withval/bin/fluid" && FLUID="$withval/bin/fluid"
 fi
 
 
@@ -3549,6 +3549,55 @@ fi
 
 
 
+echo $ac_n "checking whether certain fragile casting works""... $ac_c" 1>&6
+echo "configure:3554: checking whether certain fragile casting works" >&5
+if eval "test \"`echo '$''{'pose_cv_return_casting_ok'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test "$cross_compiling" = yes; then
+  pose_cv_return_casting_ok="assuming yes"
+else
+  cat > conftest.$ac_ext <<EOF
+#line 3562 "configure"
+#include "confdefs.h"
+
+		struct point { short x, y; };
+		point foo (long fX, long fY)
+		{
+			short pt[2]; pt[0] = fX; pt[1] = fY; return *(point*)pt;
+		}
+		int main()
+		{
+			point p = foo (28, 37);
+			return (p.x == 28 && p.y == 37)? 0 : 1;
+		}
+		
+EOF
+if { (eval echo configure:3577: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+then
+  pose_cv_return_casting_ok=yes
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  pose_cv_return_casting_ok=no
+fi
+rm -fr conftest*
+fi
+
+fi
+
+echo "$ac_t""$pose_cv_return_casting_ok" 1>&6
+
+if test "$pose_cv_return_casting_ok" = no; then
+	cat >> confdefs.h <<\EOF
+#define BROKEN_RETURN_CASTING 1
+EOF
+
+fi
+
+
+
 cat > confcache <<\EOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -3607,44 +3656,408 @@ ac_compile='${CXX-g++} -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext 1>&5'
 ac_link='${CXX-g++} -o conftest${ac_exeext} $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
 cross_compiling=$ac_cv_prog_cxx_cross
 
-echo $ac_n "checking for 'int fl_height (void)' in -lfltk""... $ac_c" 1>&6
-echo "configure:3612: checking for 'int fl_height (void)' in -lfltk" >&5
-if eval "test \"`echo '$''{'pose_cv_lib_fltk_found'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  cat > conftest.$ac_ext <<EOF
-#line 3617 "configure"
+
+
+
+
+
+echo $ac_n "checking for fl_contrast in -lfltk""... $ac_c" 1>&6
+echo "configure:3666: checking for fl_contrast in -lfltk" >&5
+cat > conftest.$ac_ext <<EOF
+#line 3668 "configure"
 #include "confdefs.h"
-#include <Fl/fl_draw.H>
+#include <FL/Enumerations.H>
 int main() {
-fl_height ();
+fl_contrast (FL_BLACK, FL_BLACK);
 ; return 0; }
 EOF
-if { (eval echo configure:3624: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3675: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
-  pose_cv_lib_fltk_found=yes
+  result=yes
 else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
   rm -rf conftest*
-  pose_cv_lib_fltk_found=no
-fi
-rm -f conftest*
-fi
-
-echo "$ac_t""$pose_cv_lib_fltk_found" 1>&6
-
-LIBS="$save_LIBS"
-
-if test $pose_cv_lib_fltk_found = yes; then
-	cat >> confdefs.h <<\EOF
-#define HAVE_LIBFLTK 1
+  cat > conftest.$ac_ext <<EOF
+#line 3683 "configure"
+#include "confdefs.h"
+#include <FL/Enumerations.H>
+int main() {
+contrast (FL_BLACK, FL_BLACK);
+; return 0; }
+EOF
+if { (eval echo configure:3690: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  result=contrast
+		cat >> confdefs.h <<\EOF
+#define fl_contrast contrast
 EOF
 
 else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  result=no
+fi
+rm -f conftest*
+fi
+rm -f conftest*
+echo "$ac_t""$result" 1>&6
+if test $result = no; then
+	{ echo "configure: error: *** FLTK *must* be installed before running configure. ***" 1>&2; exit 1; }
+fi
+echo $ac_n "checking for fl_inactive in -lfltk""... $ac_c" 1>&6
+echo "configure:3711: checking for fl_inactive in -lfltk" >&5
+cat > conftest.$ac_ext <<EOF
+#line 3713 "configure"
+#include "confdefs.h"
+#include <FL/Enumerations.H>
+int main() {
+fl_inactive (FL_BLACK);
+; return 0; }
+EOF
+if { (eval echo configure:3720: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  result=yes
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  cat > conftest.$ac_ext <<EOF
+#line 3728 "configure"
+#include "confdefs.h"
+#include <FL/Enumerations.H>
+int main() {
+inactive (FL_BLACK);
+; return 0; }
+EOF
+if { (eval echo configure:3735: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  result=inactive
+		cat >> confdefs.h <<\EOF
+#define fl_inactive inactive
+EOF
+
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  result=no
+fi
+rm -f conftest*
+fi
+rm -f conftest*
+echo "$ac_t""$result" 1>&6
+if test $result = no; then
+	{ echo "configure: error: *** FLTK *must* be installed before running configure. ***" 1>&2; exit 1; }
+fi
+echo $ac_n "checking for fl_filename_absolute in -lfltk""... $ac_c" 1>&6
+echo "configure:3756: checking for fl_filename_absolute in -lfltk" >&5
+cat > conftest.$ac_ext <<EOF
+#line 3758 "configure"
+#include "confdefs.h"
+#include <FL/filename.H>
+int main() {
+fl_filename_absolute ("", "");
+; return 0; }
+EOF
+if { (eval echo configure:3765: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  result=yes
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  cat > conftest.$ac_ext <<EOF
+#line 3773 "configure"
+#include "confdefs.h"
+#include <FL/filename.H>
+int main() {
+filename_absolute ("", "");
+; return 0; }
+EOF
+if { (eval echo configure:3780: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  result=filename_absolute
+		cat >> confdefs.h <<\EOF
+#define fl_filename_absolute filename_absolute
+EOF
+
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  result=no
+fi
+rm -f conftest*
+fi
+rm -f conftest*
+echo "$ac_t""$result" 1>&6
+if test $result = no; then
+	{ echo "configure: error: *** FLTK *must* be installed before running configure. ***" 1>&2; exit 1; }
+fi
+echo $ac_n "checking for fl_filename_ext in -lfltk""... $ac_c" 1>&6
+echo "configure:3801: checking for fl_filename_ext in -lfltk" >&5
+cat > conftest.$ac_ext <<EOF
+#line 3803 "configure"
+#include "confdefs.h"
+#include <FL/filename.H>
+int main() {
+fl_filename_ext ("");
+; return 0; }
+EOF
+if { (eval echo configure:3810: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  result=yes
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  cat > conftest.$ac_ext <<EOF
+#line 3818 "configure"
+#include "confdefs.h"
+#include <FL/filename.H>
+int main() {
+filename_ext ("");
+; return 0; }
+EOF
+if { (eval echo configure:3825: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  result=filename_ext
+		cat >> confdefs.h <<\EOF
+#define fl_filename_ext filename_ext
+EOF
+
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  result=no
+fi
+rm -f conftest*
+fi
+rm -f conftest*
+echo "$ac_t""$result" 1>&6
+if test $result = no; then
+	{ echo "configure: error: *** FLTK *must* be installed before running configure. ***" 1>&2; exit 1; }
+fi
+echo $ac_n "checking for fl_filename_isdir in -lfltk""... $ac_c" 1>&6
+echo "configure:3846: checking for fl_filename_isdir in -lfltk" >&5
+cat > conftest.$ac_ext <<EOF
+#line 3848 "configure"
+#include "confdefs.h"
+#include <FL/filename.H>
+int main() {
+fl_filename_isdir ("");
+; return 0; }
+EOF
+if { (eval echo configure:3855: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  result=yes
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  cat > conftest.$ac_ext <<EOF
+#line 3863 "configure"
+#include "confdefs.h"
+#include <FL/filename.H>
+int main() {
+filename_isdir ("");
+; return 0; }
+EOF
+if { (eval echo configure:3870: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  result=filename_isdir
+		cat >> confdefs.h <<\EOF
+#define fl_filename_isdir filename_isdir
+EOF
+
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  result=no
+fi
+rm -f conftest*
+fi
+rm -f conftest*
+echo "$ac_t""$result" 1>&6
+if test $result = no; then
+	{ echo "configure: error: *** FLTK *must* be installed before running configure. ***" 1>&2; exit 1; }
+fi
+echo $ac_n "checking for fl_filename_list in -lfltk""... $ac_c" 1>&6
+echo "configure:3891: checking for fl_filename_list in -lfltk" >&5
+cat > conftest.$ac_ext <<EOF
+#line 3893 "configure"
+#include "confdefs.h"
+#include <FL/filename.H>
+int main() {
+fl_filename_list ("", 0);
+; return 0; }
+EOF
+if { (eval echo configure:3900: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  result=yes
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  cat > conftest.$ac_ext <<EOF
+#line 3908 "configure"
+#include "confdefs.h"
+#include <FL/filename.H>
+int main() {
+filename_list ("", 0);
+; return 0; }
+EOF
+if { (eval echo configure:3915: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  result=filename_list
+		cat >> confdefs.h <<\EOF
+#define fl_filename_list filename_list
+EOF
+
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  result=no
+fi
+rm -f conftest*
+fi
+rm -f conftest*
+echo "$ac_t""$result" 1>&6
+if test $result = no; then
+	{ echo "configure: error: *** FLTK *must* be installed before running configure. ***" 1>&2; exit 1; }
+fi
+echo $ac_n "checking for fl_filename_match in -lfltk""... $ac_c" 1>&6
+echo "configure:3936: checking for fl_filename_match in -lfltk" >&5
+cat > conftest.$ac_ext <<EOF
+#line 3938 "configure"
+#include "confdefs.h"
+#include <FL/filename.H>
+int main() {
+fl_filename_match ("", "");
+; return 0; }
+EOF
+if { (eval echo configure:3945: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  result=yes
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  cat > conftest.$ac_ext <<EOF
+#line 3953 "configure"
+#include "confdefs.h"
+#include <FL/filename.H>
+int main() {
+filename_match ("", "");
+; return 0; }
+EOF
+if { (eval echo configure:3960: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  result=filename_match
+		cat >> confdefs.h <<\EOF
+#define fl_filename_match filename_match
+EOF
+
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  result=no
+fi
+rm -f conftest*
+fi
+rm -f conftest*
+echo "$ac_t""$result" 1>&6
+if test $result = no; then
+	{ echo "configure: error: *** FLTK *must* be installed before running configure. ***" 1>&2; exit 1; }
+fi
+echo $ac_n "checking for fl_filename_setext in -lfltk""... $ac_c" 1>&6
+echo "configure:3981: checking for fl_filename_setext in -lfltk" >&5
+cat > conftest.$ac_ext <<EOF
+#line 3983 "configure"
+#include "confdefs.h"
+#include <FL/filename.H>
+int main() {
+fl_filename_setext ("", "");
+; return 0; }
+EOF
+if { (eval echo configure:3990: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  result=yes
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  cat > conftest.$ac_ext <<EOF
+#line 3998 "configure"
+#include "confdefs.h"
+#include <FL/filename.H>
+int main() {
+filename_setext ("", "");
+; return 0; }
+EOF
+if { (eval echo configure:4005: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  result=filename_setext
+		cat >> confdefs.h <<\EOF
+#define fl_filename_setext filename_setext
+EOF
+
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  result=no
+fi
+rm -f conftest*
+fi
+rm -f conftest*
+echo "$ac_t""$result" 1>&6
+if test $result = no; then
 	{ echo "configure: error: *** FLTK *must* be installed before running configure. ***" 1>&2; exit 1; }
 fi
 
+LIBS="$save_LIBS"
+
+# Extract the first word of "fluid", so it can be a program name with args.
+set dummy fluid; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:4031: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_FLUID'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$FLUID"; then
+  ac_cv_prog_FLUID="$FLUID" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_prog_FLUID="fluid"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_prog_FLUID" && ac_cv_prog_FLUID="no"
+fi
+fi
+FLUID="$ac_cv_prog_FLUID"
+if test -n "$FLUID"; then
+  echo "$ac_t""$FLUID" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+
+if test "$FLUID" = no; then
+	{ echo "configure: error: *** FLTK *must* be installed before running configure. ***" 1>&2; exit 1; }
+fi
 
 
 FLAGS="$FLAGS_COMMON $FLAGS_OPTIMIZE $FLAGS_PROFILE $FLAGS_PALM_PROFILE $FLAGS_DEBUG"
@@ -3852,6 +4265,7 @@ s%@X_EXTRA_LIBS@%$X_EXTRA_LIBS%g
 s%@ALLOCA@%$ALLOCA%g
 s%@CXXCPP@%$CXXCPP%g
 s%@GLLIB@%$GLLIB%g
+s%@FLUID@%$FLUID%g
 s%@AR@%$AR%g
 s%@POSER_CFLAGS@%$POSER_CFLAGS%g
 s%@POSER_CXXFLAGS@%$POSER_CXXFLAGS%g
